"""added api_id field to Pokemon model for that pokemon's id value returned from the api call

Revision ID: 367d85d8e75f
Revises: 0cf9d311d849
Create Date: 2022-07-17 17:08:31.918111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367d85d8e75f'
down_revision = '0cf9d311d849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('api_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'pokemon', ['api_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='unique')
    op.drop_column('pokemon', 'api_id')
    # ### end Alembic commands ###
