"""changed User and Pokemon models to make it one-to-many from User to Pokemon rather than moany to many and deleted collection table.

Revision ID: 3ba9d3ab4bc0
Revises: 367d85d8e75f
Create Date: 2022-07-18 19:16:27.441040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba9d3ab4bc0'
down_revision = '367d85d8e75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    op.add_column('pokemon', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pokemon', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'user_id')
    op.create_table('collection',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name='collection_pokemon_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='collection_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'pokemon_id', name='collection_pkey')
    )
    # ### end Alembic commands ###
